//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia_IFM02B2_Project_Website.ACD_Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyUser", Namespace="http://schemas.datacontract.org/2004/07/Academia_IFM02B2_Project_Service")]
    [System.SerializableAttribute()]
    public partial class MyUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contacts {
            get {
                return this.contactsField;
            }
            set {
                if ((object.ReferenceEquals(this.contactsField, value) != true)) {
                    this.contactsField = value;
                    this.RaisePropertyChanged("contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string passwd {
            get {
                return this.passwdField;
            }
            set {
                if ((object.ReferenceEquals(this.passwdField, value) != true)) {
                    this.passwdField = value;
                    this.RaisePropertyChanged("passwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userType {
            get {
                return this.userTypeField;
            }
            set {
                if ((this.userTypeField.Equals(value) != true)) {
                    this.userTypeField = value;
                    this.RaisePropertyChanged("userType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Academia_IFM02B2_Project_Service")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((this.RegDateField.Equals(value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tutor", Namespace="http://schemas.datacontract.org/2004/07/Academia_IFM02B2_Project_Service")]
    [System.SerializableAttribute()]
    public partial class Tutor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AboutMeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TutorsIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AboutMe {
            get {
                return this.AboutMeField;
            }
            set {
                if ((object.ReferenceEquals(this.AboutMeField, value) != true)) {
                    this.AboutMeField = value;
                    this.RaisePropertyChanged("AboutMe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qualification {
            get {
                return this.QualificationField;
            }
            set {
                if ((object.ReferenceEquals(this.QualificationField, value) != true)) {
                    this.QualificationField = value;
                    this.RaisePropertyChanged("Qualification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((this.RegDateField.Equals(value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TutorsId {
            get {
                return this.TutorsIdField;
            }
            set {
                if ((this.TutorsIdField.Equals(value) != true)) {
                    this.TutorsIdField = value;
                    this.RaisePropertyChanged("TutorsId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyTutor", Namespace="http://schemas.datacontract.org/2004/07/Academia_IFM02B2_Project_Service")]
    [System.SerializableAttribute()]
    public partial class MyTutor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aboutMeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string postalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string qualificationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aboutMe {
            get {
                return this.aboutMeField;
            }
            set {
                if ((object.ReferenceEquals(this.aboutMeField, value) != true)) {
                    this.aboutMeField = value;
                    this.RaisePropertyChanged("aboutMe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.postalCodeField, value) != true)) {
                    this.postalCodeField = value;
                    this.RaisePropertyChanged("postalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                if ((object.ReferenceEquals(this.provinceField, value) != true)) {
                    this.provinceField = value;
                    this.RaisePropertyChanged("province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string qualification {
            get {
                return this.qualificationField;
            }
            set {
                if ((object.ReferenceEquals(this.qualificationField, value) != true)) {
                    this.qualificationField = value;
                    this.RaisePropertyChanged("qualification");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactUSs", Namespace="http://schemas.datacontract.org/2004/07/Academia_IFM02B2_Project_Service")]
    [System.SerializableAttribute()]
    public partial class ContactUSs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactId {
            get {
                return this.ContactIdField;
            }
            set {
                if ((this.ContactIdField.Equals(value) != true)) {
                    this.ContactIdField = value;
                    this.RaisePropertyChanged("ContactId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Registered {
            get {
                return this.RegisteredField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisteredField, value) != true)) {
                    this.RegisteredField = value;
                    this.RaisePropertyChanged("Registered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subject", Namespace="http://schemas.datacontract.org/2004/07/Academia_IFM02B2_Project_Service")]
    [System.SerializableAttribute()]
    public partial class Subject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TutorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((this.SubjectIdField.Equals(value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TutorId {
            get {
                return this.TutorIdField;
            }
            set {
                if ((this.TutorIdField.Equals(value) != true)) {
                    this.TutorIdField = value;
                    this.RaisePropertyChanged("TutorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MySubject", Namespace="http://schemas.datacontract.org/2004/07/Academia_IFM02B2_Project_Service")]
    [System.SerializableAttribute()]
    public partial class MySubject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tutorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tutorId {
            get {
                return this.tutorIdField;
            }
            set {
                if ((this.tutorIdField.Equals(value) != true)) {
                    this.tutorIdField = value;
                    this.RaisePropertyChanged("tutorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Package", Namespace="http://schemas.datacontract.org/2004/07/Academia_IFM02B2_Project_Service")]
    [System.SerializableAttribute()]
    public partial class Package : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyContact", Namespace="http://schemas.datacontract.org/2004/07/Academia_IFM02B2_Project_Service")]
    [System.SerializableAttribute()]
    public partial class MyContact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string registeredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string registered {
            get {
                return this.registeredField;
            }
            set {
                if ((object.ReferenceEquals(this.registeredField, value) != true)) {
                    this.registeredField = value;
                    this.RaisePropertyChanged("registered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                if ((object.ReferenceEquals(this.subjectField, value) != true)) {
                    this.subjectField = value;
                    this.RaisePropertyChanged("subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ACD_Reference.IACD_Service")]
    public interface IACD_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/Login", ReplyAction="http://tempuri.org/IACD_Service/LoginResponse")]
        int Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/Login", ReplyAction="http://tempuri.org/IACD_Service/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/Register", ReplyAction="http://tempuri.org/IACD_Service/RegisterResponse")]
        int Register(Academia_IFM02B2_Project_Website.ACD_Reference.MyUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/Register", ReplyAction="http://tempuri.org/IACD_Service/RegisterResponse")]
        System.Threading.Tasks.Task<int> RegisterAsync(Academia_IFM02B2_Project_Website.ACD_Reference.MyUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getUser", ReplyAction="http://tempuri.org/IACD_Service/getUserResponse")]
        Academia_IFM02B2_Project_Website.ACD_Reference.User getUser(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getUser", ReplyAction="http://tempuri.org/IACD_Service/getUserResponse")]
        System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.User> getUserAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getTutor", ReplyAction="http://tempuri.org/IACD_Service/getTutorResponse")]
        Academia_IFM02B2_Project_Website.ACD_Reference.Tutor getTutor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getTutor", ReplyAction="http://tempuri.org/IACD_Service/getTutorResponse")]
        System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.Tutor> getTutorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getAllTutors", ReplyAction="http://tempuri.org/IACD_Service/getAllTutorsResponse")]
        Academia_IFM02B2_Project_Website.ACD_Reference.Tutor[] getAllTutors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getAllTutors", ReplyAction="http://tempuri.org/IACD_Service/getAllTutorsResponse")]
        System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.Tutor[]> getAllTutorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/AddTutor", ReplyAction="http://tempuri.org/IACD_Service/AddTutorResponse")]
        int AddTutor(Academia_IFM02B2_Project_Website.ACD_Reference.MyTutor tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/AddTutor", ReplyAction="http://tempuri.org/IACD_Service/AddTutorResponse")]
        System.Threading.Tasks.Task<int> AddTutorAsync(Academia_IFM02B2_Project_Website.ACD_Reference.MyTutor tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getAllUsers", ReplyAction="http://tempuri.org/IACD_Service/getAllUsersResponse")]
        Academia_IFM02B2_Project_Website.ACD_Reference.User[] getAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getAllUsers", ReplyAction="http://tempuri.org/IACD_Service/getAllUsersResponse")]
        System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.User[]> getAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/UpdateUser", ReplyAction="http://tempuri.org/IACD_Service/UpdateUserResponse")]
        int UpdateUser(Academia_IFM02B2_Project_Website.ACD_Reference.MyUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/UpdateUser", ReplyAction="http://tempuri.org/IACD_Service/UpdateUserResponse")]
        System.Threading.Tasks.Task<int> UpdateUserAsync(Academia_IFM02B2_Project_Website.ACD_Reference.MyUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/UpdateTutor", ReplyAction="http://tempuri.org/IACD_Service/UpdateTutorResponse")]
        int UpdateTutor(Academia_IFM02B2_Project_Website.ACD_Reference.MyTutor tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/UpdateTutor", ReplyAction="http://tempuri.org/IACD_Service/UpdateTutorResponse")]
        System.Threading.Tasks.Task<int> UpdateTutorAsync(Academia_IFM02B2_Project_Website.ACD_Reference.MyTutor tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getAllContactUs", ReplyAction="http://tempuri.org/IACD_Service/getAllContactUsResponse")]
        Academia_IFM02B2_Project_Website.ACD_Reference.ContactUSs[] getAllContactUs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getAllContactUs", ReplyAction="http://tempuri.org/IACD_Service/getAllContactUsResponse")]
        System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.ContactUSs[]> getAllContactUsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getSubject", ReplyAction="http://tempuri.org/IACD_Service/getSubjectResponse")]
        Academia_IFM02B2_Project_Website.ACD_Reference.Subject getSubject(int tutId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getSubject", ReplyAction="http://tempuri.org/IACD_Service/getSubjectResponse")]
        System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.Subject> getSubjectAsync(int tutId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getAllSubjects", ReplyAction="http://tempuri.org/IACD_Service/getAllSubjectsResponse")]
        Academia_IFM02B2_Project_Website.ACD_Reference.Subject[] getAllSubjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getAllSubjects", ReplyAction="http://tempuri.org/IACD_Service/getAllSubjectsResponse")]
        System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.Subject[]> getAllSubjectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/AddSubject", ReplyAction="http://tempuri.org/IACD_Service/AddSubjectResponse")]
        int AddSubject(Academia_IFM02B2_Project_Website.ACD_Reference.MySubject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/AddSubject", ReplyAction="http://tempuri.org/IACD_Service/AddSubjectResponse")]
        System.Threading.Tasks.Task<int> AddSubjectAsync(Academia_IFM02B2_Project_Website.ACD_Reference.MySubject subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getPackage", ReplyAction="http://tempuri.org/IACD_Service/getPackageResponse")]
        Academia_IFM02B2_Project_Website.ACD_Reference.Package getPackage(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getPackage", ReplyAction="http://tempuri.org/IACD_Service/getPackageResponse")]
        System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.Package> getPackageAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getAllPackages", ReplyAction="http://tempuri.org/IACD_Service/getAllPackagesResponse")]
        Academia_IFM02B2_Project_Website.ACD_Reference.Package[] getAllPackages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/getAllPackages", ReplyAction="http://tempuri.org/IACD_Service/getAllPackagesResponse")]
        System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.Package[]> getAllPackagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/AddContactUs", ReplyAction="http://tempuri.org/IACD_Service/AddContactUsResponse")]
        int AddContactUs(Academia_IFM02B2_Project_Website.ACD_Reference.MyContact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IACD_Service/AddContactUs", ReplyAction="http://tempuri.org/IACD_Service/AddContactUsResponse")]
        System.Threading.Tasks.Task<int> AddContactUsAsync(Academia_IFM02B2_Project_Website.ACD_Reference.MyContact contact);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IACD_ServiceChannel : Academia_IFM02B2_Project_Website.ACD_Reference.IACD_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ACD_ServiceClient : System.ServiceModel.ClientBase<Academia_IFM02B2_Project_Website.ACD_Reference.IACD_Service>, Academia_IFM02B2_Project_Website.ACD_Reference.IACD_Service {
        
        public ACD_ServiceClient() {
        }
        
        public ACD_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ACD_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ACD_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ACD_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public int Register(Academia_IFM02B2_Project_Website.ACD_Reference.MyUser user) {
            return base.Channel.Register(user);
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(Academia_IFM02B2_Project_Website.ACD_Reference.MyUser user) {
            return base.Channel.RegisterAsync(user);
        }
        
        public Academia_IFM02B2_Project_Website.ACD_Reference.User getUser(int Id) {
            return base.Channel.getUser(Id);
        }
        
        public System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.User> getUserAsync(int Id) {
            return base.Channel.getUserAsync(Id);
        }
        
        public Academia_IFM02B2_Project_Website.ACD_Reference.Tutor getTutor(int id) {
            return base.Channel.getTutor(id);
        }
        
        public System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.Tutor> getTutorAsync(int id) {
            return base.Channel.getTutorAsync(id);
        }
        
        public Academia_IFM02B2_Project_Website.ACD_Reference.Tutor[] getAllTutors() {
            return base.Channel.getAllTutors();
        }
        
        public System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.Tutor[]> getAllTutorsAsync() {
            return base.Channel.getAllTutorsAsync();
        }
        
        public int AddTutor(Academia_IFM02B2_Project_Website.ACD_Reference.MyTutor tutor) {
            return base.Channel.AddTutor(tutor);
        }
        
        public System.Threading.Tasks.Task<int> AddTutorAsync(Academia_IFM02B2_Project_Website.ACD_Reference.MyTutor tutor) {
            return base.Channel.AddTutorAsync(tutor);
        }
        
        public Academia_IFM02B2_Project_Website.ACD_Reference.User[] getAllUsers() {
            return base.Channel.getAllUsers();
        }
        
        public System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.User[]> getAllUsersAsync() {
            return base.Channel.getAllUsersAsync();
        }
        
        public int UpdateUser(Academia_IFM02B2_Project_Website.ACD_Reference.MyUser user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<int> UpdateUserAsync(Academia_IFM02B2_Project_Website.ACD_Reference.MyUser user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public int UpdateTutor(Academia_IFM02B2_Project_Website.ACD_Reference.MyTutor tutor) {
            return base.Channel.UpdateTutor(tutor);
        }
        
        public System.Threading.Tasks.Task<int> UpdateTutorAsync(Academia_IFM02B2_Project_Website.ACD_Reference.MyTutor tutor) {
            return base.Channel.UpdateTutorAsync(tutor);
        }
        
        public Academia_IFM02B2_Project_Website.ACD_Reference.ContactUSs[] getAllContactUs() {
            return base.Channel.getAllContactUs();
        }
        
        public System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.ContactUSs[]> getAllContactUsAsync() {
            return base.Channel.getAllContactUsAsync();
        }
        
        public Academia_IFM02B2_Project_Website.ACD_Reference.Subject getSubject(int tutId) {
            return base.Channel.getSubject(tutId);
        }
        
        public System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.Subject> getSubjectAsync(int tutId) {
            return base.Channel.getSubjectAsync(tutId);
        }
        
        public Academia_IFM02B2_Project_Website.ACD_Reference.Subject[] getAllSubjects() {
            return base.Channel.getAllSubjects();
        }
        
        public System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.Subject[]> getAllSubjectsAsync() {
            return base.Channel.getAllSubjectsAsync();
        }
        
        public int AddSubject(Academia_IFM02B2_Project_Website.ACD_Reference.MySubject subject) {
            return base.Channel.AddSubject(subject);
        }
        
        public System.Threading.Tasks.Task<int> AddSubjectAsync(Academia_IFM02B2_Project_Website.ACD_Reference.MySubject subject) {
            return base.Channel.AddSubjectAsync(subject);
        }
        
        public Academia_IFM02B2_Project_Website.ACD_Reference.Package getPackage(int id) {
            return base.Channel.getPackage(id);
        }
        
        public System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.Package> getPackageAsync(int id) {
            return base.Channel.getPackageAsync(id);
        }
        
        public Academia_IFM02B2_Project_Website.ACD_Reference.Package[] getAllPackages() {
            return base.Channel.getAllPackages();
        }
        
        public System.Threading.Tasks.Task<Academia_IFM02B2_Project_Website.ACD_Reference.Package[]> getAllPackagesAsync() {
            return base.Channel.getAllPackagesAsync();
        }
        
        public int AddContactUs(Academia_IFM02B2_Project_Website.ACD_Reference.MyContact contact) {
            return base.Channel.AddContactUs(contact);
        }
        
        public System.Threading.Tasks.Task<int> AddContactUsAsync(Academia_IFM02B2_Project_Website.ACD_Reference.MyContact contact) {
            return base.Channel.AddContactUsAsync(contact);
        }
    }
}
